SpMarket/SpMarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('sp_user.urls',namespace='sp_user')),#用户主页
    url(r'^goods/', include('sp_goods.urls',namespace='sp_goods')),#用户主页
    url(r'^cart/', include('sp_cart.urls',namespace='sp_cart')),#用户主页
    url(r'^order/', include('sp_order.urls',namespace='sp_order')),#用户主页
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),#在主路由中配置 ckeditor 上传文件使用到的url地址
#全文搜索框架
    url(r'^search/', include('haystack.urls')),
]

SpMarket/apps/sp_user/urls.py
from django.conf.urls import url
from sp_user.views import *

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),  # 登录
    url(r'^register/$', RegisterView.as_view(), name='register'),  # 注册
    url(r'^member/$', MemberView.as_view(), name='member'),  # 主页
    url(r'^forget/$', ForgetPassView.as_view(), name='forget'),  # 忘记密码
    url(r'^info/$', InfomationView.as_view(), name='info'),  # 个人资料
    url(r'^sendMsg/$', send_msg_phone, name="sendMsg"),  # 短信地址

]

SpMarket/apps/sp_user/models.py
from django.db import models

# Create your models here.
from db.base_model import BaseModel


class Users(BaseModel):
    sex_choices = (
        (1, '男'),
        (2, "女"),
        (3, "保密"),
    )
    nickname = models.CharField(verbose_name='昵称',
                                max_length=20,
                                null=True,
                                blank=True,
                                )
    phone = models.CharField(verbose_name='手机号码',
                             unique=True,
                             max_length=12)
    password = models.CharField(verbose_name='密码',
                                max_length=64,
                                )
    gender = models.SmallIntegerField(verbose_name='性别',
                                      default=3,
                                      choices=sex_choices,
                                      )
    birthday = models.DateField(verbose_name='出生日期',
                                null=True,
                                blank=True,
                                )
    school_name = models.CharField(verbose_name='学校名称',
                                   max_length=50,
                                   null=True, blank=True,
                                   )
    address = models.CharField(verbose_name='学校详细地址',
                               max_length=100,
                               null=True,
                               blank=True,
                               )
    hometown = models.CharField(verbose_name='老家',
                                max_length=100,
                                null=True, blank=True,
                                )
    head = models.ImageField(upload_to='head/%Y%m/',default='head/memtx.png',verbose_name='用户头像')
    class Meta:
        db_table = "sp_users"
        verbose_name = '用户管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.phone

SpMarket/apps/sp_user/forms.py
from django import forms

from sp_user.helper import set_password
from sp_user.models import Users


# 注册
class RegisterModelForm(forms.ModelForm):
    password1 = forms.CharField(max_length=16,
                                min_length=6,
                                error_messages={
                                    'required': '密码必须填写',
                                    'max_length': '密码长度不能超过16个字符',
                                    'min_length': '密码长度必须大于6个'
                                }
                                )
    password2 = forms.CharField(max_length=16,
                                min_length=6,
                                error_messages={
                                    'required': '密码必须填写',
                                    'max_length': '密码长度不能超过16个字符',
                                    'min_length': '密码长度必须大于6个'
                                }

                                )

    class Meta:
        model = Users
        fields = ['phone', ]
        error_messages = {
            'phone': {
                'required': '手机号码必须填写'
            }
        }

    def clean_password2(self):
        pwd1 = self.cleaned_data.get('password1')
        pwd2 = self.cleaned_data.get('password2')

        if pwd1 != pwd2 and pwd1 and pwd2:
            raise forms.ValidationError('请重新输入密码,您的两次密码输入不一致')
        return pwd2

    # 验证手机号是不是唯一
    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        rs = Users.objects.filter(phone=phone).exists()
        if rs:
            raise forms.ValidationError('手机号码已经注册')
        return phone


# 登录
class LoginForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = ['phone', 'password']
        error_messages = {
            'phone': {
                'required': '手机号码必须填写',
            },
            'password': {
                'required': '密码未填写,请填写',
                'min_length': '密码不得小于6个',
                'max_length': '密码不得大于64个',
            }
        }

    widgets = {
        'phone': forms.TextInput(attrs={'class': 'login-name', 'placeholder': '请输入手机号'}),
        'password': forms.PasswordInput(attrs={'class': 'login-password', 'placeholder': '请输入密码'}),
    }

    def clean(self):
        cleaned_data = self.cleaned_data
        # 获取数据
        phone = cleaned_data.get('phone')
        password = cleaned_data.get('password')
        # 验证手机号码是否存在
        if all([phone, password]):
            # 根据手机号码获取用户
            try:
                user = Users.objects.get(phone=phone)
            except Users.DoesNotExist:
                raise forms.ValidationError({"phone": "该用户不存在!"})
            # 判断密码是否正确
            if user.password != set_password(password):
                raise forms.ValidationError({"password": "密码填写错误!"})
            # 将用户信息保存到cleaned_data中
            cleaned_data['user'] = user
            return cleaned_data
        else:
            return cleaned_data


# 修改
class UserChangeModelForm(forms.ModelForm):
    class Meta:
        model = Users
        # 排除不用的字段
        exclude = ['create_time,', 'update_time', 'is_delete', 'password']
        # 修改的样式
        widgets = {
            "nickname": forms.TextInput(attrs={'class': "infor-tele", "placeholder": "请填写昵称"}),
            "gender": forms.RadioSelect(),
            "birthday": forms.DateInput(attrs={'class': "infor-tele", "type": 'date'}, format='%Y-%m-%d'),
            "school_name": forms.TextInput(attrs={'class': "infor-tele", "placeholder": "请输入学校"}),
            "address": forms.TextInput(attrs={'class': "infor-tele", "placeholder": "请输入地址"}),
            "hometown": forms.TextInput(attrs={'class': "infor-tele", "placeholder": "请输入老家"}),
            "phone": forms.TextInput(attrs={'class': "infor-tele", "placeholder": "请输入手机号"}),
        }

    def validate_unique(self):
        pass

SpMarket/apps/sp_user/views.py
import random
import re
import uuid

from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, JsonResponse
# Create your views here.
from django.utils.decorators import method_decorator
from django.views import View
from django_redis import get_redis_connection

from sp_user.forms import RegisterModelForm, LoginForm, UserChangeModelForm
from sp_user.helper import set_password, check_phone_pwd, check_is_login, send_sms, login
from sp_user.models import Users


@check_is_login
def foo(request):
    pass


# 登录
class LoginView(View):

    def get(self, request):
        form = LoginForm()
        return render(request, 'sp_user/login.html', {'form': form})

    def post(self, request):
        data = request.POST
        form = LoginForm(data)
        if form.is_valid():
            # 和数据库验证
            data = form.cleaned_data
            phone = data.get('phone')
            password = data.get('password')
            user = check_phone_pwd(phone, password)
            if user:
                # 验证成功后,将用户登录标识符保存到session
                # request.session.clear()
                request.session['ID'] = user.pk
                request.session['phone'] = user.phone
                request.session.set_expiry(0)
                if request.GET.get("next"):
                    return redirect(request.GET.get("next"))
                else:
                    # 跳转到用户中心
                    return redirect("sp_user:member")
            else:
                context = {
                    'errors': form.errors,
                }
                return render(request, 'sp_user/login.html', context)


# 注册
class RegisterView(View):
    def get(self, request):
        return render(request, 'sp_user/reg.html')

    def post(self, request):
        # 接受数据
        data = request.POST
        form = RegisterModelForm(data)
        if form.is_valid():
            # 处理数据
            data = form.cleaned_data
            password = data.get('password2')
            password = set_password(password)
            Users.objects.create(phone=data.get('phone'), password=password)
            # 响应
            return redirect('sp_user:login')
        else:
            context = {
                'errors': form.errors
            }
            return render(request, 'sp_user/reg.html', context)

    # 忘记密码


class ForgetPassView(View):
    def get(self, request):
        return render(request, 'sp_user/forgetpassword.html')

    def post(self, request):
        pass


@check_is_login
def center(request):
    # 如果session中没有用户ID,说明没有登录，就跳转到登录页面
    # if request.session.get("ID") is None:
    #     return redirect("/user/login/")
    return render(request, "sp_user/member.html")

    # 个人中心


class MemberView(View):

    def get(self, request):
        context = {
            'phone': request.session.get('phone')
        }
        return render(request, 'sp_user/member.html', context)

    def post(self, request):
        pass

    # 视图类的装饰
    @method_decorator(check_is_login)
    def dispatch(self, request, *args, **kwargs):
        return super(MemberView, self).dispatch(request, *args, **kwargs)

    # 个人资料


class InfomationView(View):

    def get(self, request):
        id = request.session.get('ID')
        user = Users.objects.filter(pk=id).values().first()
        user_change_form = UserChangeModelForm(user)
        return render(request, 'sp_user/infor.html', {"form": user_change_form})

    def post(self, request):
        # 获取需要更改的数据
        user = Users.objects.filter(pk=request.session.get('ID')).first()
        data = request.POST
        user_change_form = UserChangeModelForm(data, instance=user)
        if user_change_form.is_valid():
            user_change_form.save()
            return redirect(reverse('sp_user:member'))
        else:
            return render(request, 'sp_user/infor.html', {"form": user_change_form})

    @method_decorator(check_is_login)
    def dispatch(self, request, *args, **kwargs):
        return super(InfomationView, self).dispatch(request, *args, **kwargs)


# 发送短信的视图函数
def send_msg_phone(request):
    if request.method == 'POST':
        # 接受手机号码
        phone = request.POST.get('phone', '')  # ''指以免为NONE时报错
        # 验证手机是否错误
        phone_re = re.compile('^1[3-9]\d{9}$')
        rs = re.search(phone_re, phone)
        if not rs:
            return JsonResponse({'err': 1, 'errmsg': '手机输入的格式不正确'})
        random_code = "".join([str(random.randint(0, 9)) for _ in range(6)])  # 下划线可以作为无用的变量

        # 保存随机码到数据库中
        r = get_redis_connection('default')
        r.set(phone, random_code)
        r.expire(phone, 60)
        # 发送短信
        print(random_code)

        # 使用阿里发送短信
        __business_id = uuid.uuid1()
        params = "{\"code\":\"%s\",\"product\":\"云通信\"}" %random_code
        print(send_sms(__business_id, phone, "注册验证", "SMS_2245271", params))

        return JsonResponse({'err': 0})
    else:
        return JsonResponse({'err': 1, 'errmsg': '请求方式错误!'})

SpMarket/templates/sp_user/forgetpassword.html
{% extends 'public/base.html' %}
{% load static %}
{% block body %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">忘记密码</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>

	    <input type="text" name="mobile"  placeholder="请输入手机号" class="login-password">
	    <div class="yzm">
	    	<input type="text" class="reg-yzm" placeholder="输入验证码" />
	    	<input type="button" class="yzm-hq" value="获取验证码" />
	    </div>
	    <input type="password" name="password"  placeholder="请输入密码" class="login-password">
	    <input type="password" name="password"  placeholder="确认密码" class="login-name">
	    <input type="button" class="login-btn" value="立即提交">
{% endblock %}

SpMarket/templates/sp_user/infor.html
{% extends 'public/base.html' %}
{% load static %}
{% block body %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">个人资料</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <ul class="safty1">
            <li>
                <a href="">
                    <i style="margin-top: 25px;">头像</i>
                    <div class="infor-pic">
                         <img src="{% static 'images/m_02.png' %}"/>

                    </div>
                    <input type="file" name="head">
                </a>
            </li>
            <li>
                    <i>昵称</i>
                    {{ form.nickname }}
            </li>
            <li>
                <a href="">
                    <i>性别</i>
                    <i class="infor-tele">
                        <label class="am-radio-inline">
                            {{ form.gender.0 }}
                        </label>
                        <label class="am-radio-inline">
                            {{ form.gender.1 }}
                        </label>
                        <label class="am-radio-inline">
                            {{ form.gender.2 }}
                        </label>
                    </i>
                </a>
            </li>
            <li>
                <a href="">
                    <i>生日</i>
                    {{ form.birthday }}
                </a>
            </li>
        </ul>
        <div style="height: 10px; background: #efefef;"></div>
        <ul class="safty1">
            <li>
                <i>学校</i>
                {{ form.school_name }}
            </li>
            <li>
                <i>位置</i>
                {{ form.address }}
            </li>
            <li>
                <i>故乡</i>
                {{ form.hometown }}
            </li>
            <li>
                <i>手机</i>
                {{ form.phone }}
            </li>
        </ul>
        <button type="submit" class="login-btn">确定修改
        </button>
        <div style="height: 49px;"></div>
    </form>
{% endblock %}

SpMarket/templates/sp_user/login.html
{% extends 'public/base.html' %}
{% load static %}
{% block body %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">登录</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
    <!--<div class="login-logo">
        <img src="images/logo.png" />
    </div>-->
    <div style="height: 3rem;"></div>
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
        <input type="text" name="phone" id="mobile" placeholder="请输入用户名/手机号" class="login-name">
        <p class="am-text-secondary">{{ errors.phone }}</p>
        <input type="password" name="password" id="password" placeholder="请输入密码" class="login-password">
        <p class="am-text-success">{{ errors.password }}</p>
        <input type="submit" class="login-btn" value="我要登录">
    </form>
    <div class="agree">
        <a href="{% url 'sp_user:register' %}">免费注册</a>
        <a href="{% url 'sp_user:forget' %}" class="forget">忘记密码？</a>
    </div>
    <div class="line"></div>
    <div class="line-text">第三方账号登录</div>
    <ul class="second-login">
        <li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/sinalog.png' %}"/></a></li>
    </ul>
{% endblock %}

SpMarket/templates/sp_user/member.html
{% extends 'public/base.html' %}
{% load static %}
{% block body %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<h1 class="am-header-title">
  	            <a href="" class="">个人中心</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <div class="member">
	    	<div class="mem-tit">18384821355
	    		<a href="step.html" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
	    	</div>
	    	<div class="mem-pic">
		    	<div class="mem-pic-bg" style="background-image: url({% static 'images/memtx.png' %});"></div>
	    	</div>
	    	<ul class="member-menu">
			<li>
				<a href="records.html">
					<p class="yellow">0</p>
					<p class="black">帐户余额 </p>
				</a>
			</li>
            <li>
				<a href="integral.html">
					<p class="yellow">0</p>
					<p class="black">积分 </p>
				</a>
			</li>
			<li>
				<a href="yhq.html">
					<p class="yellow">0</p>
					<p class="black">优惠劵 </p>
				</a>
			</li>
			<li>
				<a href="collect.html">
					<p class="yellow">0</p>
					<p class="black">我的收藏 </p>
				</a>
			</li>
		</ul>
	    </div>
	    <div class="user-list">
		  	<div class="u-list-main">
		  		<img src="{% static 'images/order-pic.png' %}" width="27" />
		  		<span>我的购物订单</span>
		  		<a href="allorder.html">查看全部订单></a>
		  	</div>
		    <ul class="user-nav">
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon.png' %}"> <p>待付款</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon1.png' %}"> <p>待收货</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon2.png' %}"> <p>待评价</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon3.png' %}"> <p>退换货</p></a></li>
		    </ul>
		    <div class="u-list-main">
		  		<img src="{% static 'images/order-my.png' %}" width="27" />
		  		<span>帐户与安全</span>
		  	</div>
		    <ul class="user-nav">
		    	<li><a href="{% url 'sp_user:info' %}"> <img src="{% static 'images/1-icon4.png' %}"> <p>个人资料</p></a></li>
		    	<li><a href="gladdress.html"> <img src="{% static 'images/1-icon5.png' %}"> <p>收货地址</p></a></li>
		    	<li><a href="saftystep.html"> <img src="{% static 'images/1-icon6.png' %}"> <p>安全设置</p></a></li>
		    	<li><a href="money.html"> <img src="{% static 'images/1-icon7.png' %}"> <p>我的钱包</p></a></li>
		    </ul>
	    </div>
	    <!--导航-->
 <ul class="sq-nav" style=" background: #fff; margin-top: 1rem; border-top: 1px solid #ddd;  border-bottom: 1px solid #ddd;">
      <li>
        <div class="am-gallery-item">
            <a href="job.html" class="">
              <img src="{% static 'images/m_03.png' %}" />
              <p>我要兼职</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="recommend.html" class="">
              <img src="{% static 'images/m_04.png' %}" />
              <p>推荐有奖</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="myrecommend.html" class="">
              <img src="{% static 'images/m_05.png' %}" />
              <p>我的推荐</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/m_06.png' %}" />
              <p>我的佣金</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="yhq.html" class="">
              <img src="{% static 'images/m_02.png' %}" />
              <p>我的红包</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="message.html" class="">
              <img src="{% static 'images/m_07.png' %}" />
              <p>我的动态</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="javascript:;" class="index-qd">
              <img src="{% static 'images/m_08.png' %}" />
              <p>客服中心</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/m_09.png' %}" />
              <p>安全退出</p>
            </a>
        </div>
      </li>
      </ul>
      </div>
    <!--客服中心-->
<div class="qd-box">
	<div class="popup-title">
			<span>客服中心</span>
			<div class="popup-close"><i class="iconfont">&#xe602</i></div>
	</div>
	<div class="dq-text">
		<a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes">
			<img src="{% static 'images/contactqq.png' %}" width="50" />
			<p class="contactqq">联系QQ</p>
		</a>
		<a href="tel:0791-12345678">
			<img src="{% static 'images/contacttele.png' %}"  width="50" />
			<p class="contacttele">呼叫电话</p>
		</a>
	</div>
</div>
<!--客服中心-->
      <!--底部-->
 <div style="height: 55px;"></div>
 <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
      <ul class="am-navbar-nav am-cf am-avg-sm-5">
          <li>
            <a href="index.html" class="">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
          </li>
          <li>
            <a href="message.html" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
          </li>
          <li>
            <a href="shopcart.html" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
          </li>
          <li>
            <a href="allorder.html" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
          </li>

          <li>
            <a href="member.html" class="curr">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
          </li>
      </ul>
</div>
{% endblock %}

SpMarket/templates/sp_user/reg.html
{% extends 'public/base.html' %}
{% load static %}
{% block body %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">注册</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
    <!--<div class="login-logo">
        <img src="images/logo.png" />
    </div>-->
    <div style="height: 3rem;"></div>
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name="phone" placeholder="请输入手机号" class="login-name">
        <p class="am-text-success">{{ errors.phone.0 }}</p>
        <input type="password" name="password1" placeholder="请输入密码" class="login-password">
        <p class="am-text-warning">{{ errors.password1.0 }}</p>
        <input type="password" name="password2" placeholder="确认密码" class="login-name">
        <p class="am-text-danger">{{ errors.password2.0 }}</p>
        <div class="yzm" style="margin-top: 1.5rem;">
            <input type="text" class="reg-yzm" placeholder="输入验证码"/>
            <input type="button" class="yzm-hq" value="获取验证码"/>
        </div>
        <input type="submit" class="login-btn" value="立即注册">
    </form>

    <div class="agree">
        <input type="checkbox" name="checkbox" value="同意" checked="">&nbsp;同意
        <a href="" class="xy">《用户协议》</a>
        <div class="r-login">已有账号，请<a href="{% url 'sp_user:login' %}" class="l-login">登录</a></div>
    </div>
{% endblock %}

{% block footer_js %}
    <script>
        $(function () {
            $(".yzm-hq").on("click",function () {
                //获取手机号码
                var phone = $("input[name='phone']").val()
                // 自己判断
                var reg = /^1[3-9]\d{9}$/;
                if (!reg.test(phone)){
                    alert("手机号码格式错误!")
                    return;
                }

                var that = this;
                //验证
                $.ajax({
                    type:"post",
                    url:"{% url 'sp_user:sendMsg' %}",
                    data:{"phone":phone,"csrfmiddlewaretoken":"{{ csrf_token }}"},
                    dataType:"json",
                    success:function (data) {
                        if(data.err == 0){
                            //如果发送成功,开始倒计时
                            var count = 60;
                            $(that).css("background-color","gray");
                            //不能再点击
                            $(that).attr("disabled","disabled");
                            var timer = window.setInterval(function () {
                                //周期性执行函数
                                --count;
                                var msg = count + "秒后重新发送"
                                $(that).val(msg);
                                //当count为0的时候,才能够再次点击
                                if(count == 0){
                                    $(that).css("background-color","#76bb2a");
                                    //不能再点击
                                    $(that).removeAttr("disabled");
                                    //文字显示原来提示
                                    $(that).val("获取验证码");
                                    //清除定时
                                    window.clearInterval(timer);
                                }
                            },1000);
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}