SpMarket/SpMarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('sp_user.urls',namespace='sp_user')),#用户主页
    url(r'^goods/', include('sp_goods.urls',namespace='sp_goods')),#用户主页
    url(r'^cart/', include('sp_cart.urls',namespace='sp_cart')),#用户主页
    url(r'^order/', include('sp_order.urls',namespace='sp_order')),#用户主页
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),#在主路由中配置 ckeditor 上传文件使用到的url地址
#全文搜索框架
    url(r'^search/', include('haystack.urls')),
]

SpMarket/apps/sp_cart/urls.py
from django.conf.urls import url

from sp_cart.views import AddCartView, CartShowView

urlpatterns = [
    url(r'^addCart/$', AddCartView.as_view(), name="addCart"),
    url(r'^$', CartShowView.as_view(), name="CartShow"),
]

SpMarket/apps/sp_goods/urls.py
from django.conf.urls import url

from sp_goods.views import index , category , detail

urlpatterns = [
    url(r'^$', index, name="首页"),
    url(r'^category/(?P<cate_id>\d+)/(?P<order>\d)$', category, name="商城"),
    url(r'^(?P<id>\d+)$', detail, name="详情"),
]

SpMarket/apps/sp_user/urls.py
from django.conf.urls import url
from sp_user.views import *

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),  # 登录
    url(r'^register/$', RegisterView.as_view(), name='register'),  # 注册
    url(r'^member/$', MemberView.as_view(), name='member'),  # 主页
    url(r'^forget/$', ForgetPassView.as_view(), name='forget'),  # 忘记密码
    url(r'^info/$', InfomationView.as_view(), name='info'),  # 个人资料
    url(r'^sendMsg/$', send_msg_phone, name="sendMsg"),  # 短信地址

]

SpMarket/apps/sp_goods/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# Create your models here.
from SpMarket import settings
from db.base_model import BaseModel

is_on_sale_choices = (
    (0, "下架"),
    (1, "上架"),
)
'''商品模块'''


# 商品分类
class Category(BaseModel):
    cate_name = models.CharField(verbose_name='分类名称',
                                 max_length=20
                                 )
    brief = models.CharField(verbose_name='描述',
                             max_length=200,
                             null=True,
                             blank=True
                             )

    class Meta:
        verbose_name = "商品分类管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.cate_name


#   商品SKU单位
class Unit(BaseModel):
    name = models.CharField(max_length=20,
                            verbose_name="单位")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "商品单位管理"
        verbose_name_plural = verbose_name


# 商品SPU表
class GoodsSPU(BaseModel):
    spu_name = models.CharField(verbose_name='商品SPU名称',
                                max_length=20,
                                )

    content = RichTextUploadingField(verbose_name="商品详情")

    def __str__(self):
        return self.spu_name

    class Meta:
        verbose_name = "商品SPU"
        verbose_name_plural = verbose_name


# 商品SKU表
class GoodsSKU(BaseModel):
    sku_name = models.CharField(verbose_name='商品SKU名称',
                                max_length=100,
                                )
    brief = models.CharField(verbose_name="商品的简介",
                             max_length=200,
                             null=True,
                             blank=True,
                             )
    price = models.DecimalField(verbose_name='价格',
                                max_digits=9,
                                decimal_places=2,
                                default=0,
                                )
    unit = models.ForeignKey(to="Unit",
                             verbose_name='单位',
                             )
    stock = models.IntegerField(verbose_name='库存',
                                default=0)
    sale_num = models.IntegerField(verbose_name='销量',
                                   default=0)
    logo = models.ImageField(verbose_name='封面图片',
                             upload_to='goods/%Y%m/%d'
                             )
    category = models.ForeignKey(to="Category",
                                 verbose_name='商品分类',
                                 )
    goods_spu = models.ForeignKey(to="GoodsSPU",
                                  verbose_name="商品SPU",
                                  )
    is_on_sale = models.BooleanField(verbose_name='是否上限',
                                     choices=is_on_sale_choices,
                                     default=0)

    def __str__(self):
        return self.sku_name

    class Meta:
        verbose_name = "商品SKU管理"
        verbose_name_plural = verbose_name


#       商品相册
class Gallery(BaseModel):
    img_url = models.ImageField(verbose_name='相册图片地址',
                                upload_to='goods_gallery/%Y%m/%d')
    goods_sku = models.ForeignKey(to="GoodsSKU",
                                  verbose_name="SKU商品")

    class Meta:
        verbose_name = "商品相册管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "商品相册"


'''首页模块'''


# 首页轮播
class Banner(BaseModel):
    name = models.CharField(max_length=255,
                            verbose_name='轮播活动名')
    goods_sku = models.ForeignKey(to=GoodsSKU,
                                  verbose_name='商品SKU')
    img_url = models.ImageField(upload_to='banner/%Y%m%d',
                                verbose_name='轮播图片地址')
    order = models.SmallIntegerField(default=0,
                                     verbose_name='排序')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '首页轮播'
        verbose_name_plural = verbose_name


# 首页活动
class Activity(BaseModel):
    title = models.CharField(max_length=255,
                             verbose_name='活动名称')
    img_url = models.ImageField(verbose_name='活动图片地址',
                                upload_to='activety/%Y%m%d')
    url_site = models.CharField(verbose_name='活动的url地址',
                                max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '首页活动'
        verbose_name_plural = verbose_name

#首页活动专区
class ActivityZone(BaseModel):
    title = models.CharField(verbose_name='活动专区名称',
                             max_length=255)
    brief = models.CharField(verbose_name='活动专区的简介',
                             max_length=255,
                             null=True,
                             blank=True,
                             )
    order = models.SmallIntegerField(verbose_name='排序',
                                     default=0,)
    is_on_sale = models.BooleanField(verbose_name='是否上限',
                                     choices=is_on_sale_choices,
                                     default=0)
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '首页活动中心'
        verbose_name_plural = verbose_name

#首页活动专业商品列表
class ActivityZoneGoods(BaseModel):
    activity_zone = models.ForeignKey(to='ActivityZone',
                                      verbose_name='活动专区ID')
    goods_sku = models.ForeignKey(to="GoodsSKU",
                                  verbose_name="专区商品SKU_ID",
                                  )
    class Meta:
        verbose_name = '首页活动专业商品列表'
        verbose_name_plural = verbose_name

SpMarket/apps/sp_goods/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django_redis import get_redis_connection

from sp_goods.models import Banner, GoodsSKU, Activity, ActivityZone, Category


# 首页
def index(request):
    banners = Banner.objects.filter(is_delete=False).order_by('order')  # 轮播
    activetys = Activity.objects.filter(is_delete=False)  # 活动
    activetys_zone = ActivityZone.objects.filter(is_on_sale=True, is_delete=False).order_by('order')
    context = {
        'banners': banners,
        'activetys': activetys,
        'activetys_zone': activetys_zone
    }
    return render(request, 'sp_goods/index.html', context)



# 商城
def category(request, cate_id, order):
    try:
        cate_id = int(cate_id)
        order = int(order)
    except:
        return redirect('sp_goods:首页')
    # 关于商品分类
    category = Category.objects.filter(is_delete=False)

    # 关于物品
    if cate_id == 0:  # 默认查询第一个
        catefirst = category.first()
        cate_id = catefirst.pk

    if order == 0:
        goodsSku = GoodsSKU.objects.filter(is_delete=False, is_on_sale=True, category_id=cate_id)
    elif order == 1:
        goodsSku = GoodsSKU.objects.filter(is_on_sale=True, is_delete=False, category_id=cate_id).order_by('-sale_num')
    elif order == 2:
        goodsSku = GoodsSKU.objects.filter(is_on_sale=True, is_delete=False, category_id=cate_id).order_by('-price')
    elif order == 3:
        goodsSku = GoodsSKU.objects.filter(is_on_sale=True, is_delete=False, category_id=cate_id).order_by('price')
    elif order == 4:
        goodsSku = GoodsSKU.objects.filter(is_on_sale=True, is_delete=False, category_id=cate_id).order_by('-create_time')
    else:
        redirect('sp_goods:首页')
    #购物车商品的数量的显示
    cart_count = 0
    if request.session.get('ID'):
        user_id = request.session.get('ID')
        r =get_redis_connection('default')
        cart_key = 'cart_key_{}'.format(user_id)
        cart_values = r.hvals(cart_key)
        # print(cart_values)
        for v in cart_values:
            # print(int(v))
            cart_count += int(v)

    context = {
        'category': category,
        'goodsSku': goodsSku,
        'cate_id': cate_id,
        'order': order,
        'cart_count': cart_count,
    }

    return render(request, "sp_goods/category.html", context)


# 详情
def detail(request, id):
    try:
        goodsSku = GoodsSKU.objects.get(pk=id, is_on_sale=True)
    except GoodsSKU.DoesNotExist:
        return redirect("sp_goods:首页")

    context = {
        "goodsSku": goodsSku
    }
    return render(request, 'sp_goods/detail.html', context)

SpMarket/templates/sp_goods/category.html
{% extends 'public/base.html' %}
{% load static %}
{% block head_css %}
    <style>
        .shop-list-mid .tit a {
            color: #909090;
            font-size: 1.4rem;
            display: -webkit-box;
            -webkit-line-clamp: 1;
            -webkit-box-orient: vertical;
            overflow: hidden;
            white-space: normal;
            text-overflow: ellipsis;
        }

        .list-price {
            background: url({% if order == 2 %}
            {% static 'images/order-bot.png' %}
                {% elif order == 3 %}
                {% static 'images/order-top.png' %}
                {% else %}
                 {% static 'images/order.png' %}{% endif %}) no-repeat right center;

            padding-right: 20px;
            font-style: normal;
        }

    </style>
{% endblock %}

{% block body %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>

        <form action="/search/" method="get">
            <div class="cate-search">
                <input type="text" name="q" value="" class="cate-input" placeholder="请输入您要的搜索的产品关键词"/>
                <input type="submit" class="cate-btn" value=""/>
            </div>
        </form>

    </header>
    <div style="height: 49px;"></div>
    <ul class="list-nav">
        <li {% if order == 0 %}class="current"{% endif %}><a href="{% url 'sp_goods:商城' cate_id 0 %}">综合</a></li>
        <li {% if order == 1 %}class="current"{% endif %}><a href="{% url 'sp_goods:商城' cate_id 1 %}">销量</a></li>
        <li {% if order == 2 %}class="current"{% endif %}><a href="{% url 'sp_goods:商城' cate_id 2 %}"><i
                class="list-price">价格</i>
        <li {% if order == 4 %}class="current"{% endif %}><a href="{% url 'sp_goods:商城' cate_id 4 %}">新品</a></li>
    </ul>
    <div class="content-list">
        <div class="list-left">
            {% for cate in category %}
                <li {% if cate_id == cate.pk %}class="current"{% endif %}><a
                        href="{% url 'sp_goods:商城' cate.pk order %}">{{ cate.cate_name }}</a></li>
            {% endfor %}

        </div>
        <div class="list-right">
            <ul class="list-pro">
                {% for gs in goodsSku %}
                    <li>
                        <a href="{% url 'sp_goods:详情' gs.pk %}"><img src=" {{ MEDIA_URL }}{{ gs.logo }}"
                                                                     class="list-pic"/></a>
                        <div class="shop-list-mid" style="width: 65%;">
                            <div class="tit"><a href="detail.html">{{ gs.goods_spu.spu_name }} 包邮</a></div>
                            <div class="am-gallery-desc">￥{{ gs.price }}</div>
                            <p>销量：{{ gs.sale_num }}件</p>
                        </div>
                        <div class="list-cart">
                            <div class="d-stock ">
                                <a class="decrease">-</a>
                                <input sku_id="{{ gs.pk }}" id="num" readonly="" class="text_box" name="" type="text"
                                       value="0">
                                <a class="increase">+</a>
                            </div>
                        </div>
                        <!--<a href="" class="list-cart"><img src="images/cart.png" width="30"/></a>-->
                    </li>
                {% empty %}
                    <li>该分类下没有物品,请重新选择分类</li>
                {% endfor %}

            </ul>
            {% if goodsSkus.has_previous %}
                <a href="?p={{ goodsSkus.previous_page_number }}" class="am-btn">上一页</a>
            {% endif %}
            {% if goodsSkus.has_next %}
                <a href="?p={{ goodsSkus.next_page_number }}" class="am-btn">下一页</a>
            {% endif %}
        </div>
    </div>

    <!--底部-->
    <div style="height: 55px;"></div>
    <div class="fix-bot">
        <a href="{% url 'sp_cart:CartShow' %}"><div class="fix-bot-cart"><i id="cart_count">{{ cart_count }}</i></div></a>
        <a href="javascript:;" class="list-js">去结算</a>
        <a href="" class="list-jsk">一键快购</a>
        <!--<div class="js-text">
           <p><b>￥217.80</b></p>
           <p class="js-car">购物满50元免运费</p>
     </div>-->
    </div>
{% endblock %}

{% block footer_js %}
    <script>
        //切换价格升降
        $(function () {
            if ('{{ order }}' == 2) {
                $('.list-price').parent('a').attr('href', "{% url 'sp_goods:商城' cate_id 3 %}")
            }
            else if ('{{ order }}' == 3) {
                $('.list-price').parent('a').attr('href', "{% url 'sp_goods:商城' cate_id 2 %}")
            }
        });


        //购物数量加减
      $(function () {
                    $('.increase').click(function () {
                        var self = $(this);
                        var current_num = parseInt(self.siblings('input').val());


                        // 通过ajax请求后台, 添加数据库成功
                        var sku_id = self.siblings('input').attr('sku_id');
                        var data = {
                            "sku_id": sku_id,
                            "count": 1,
                            "csrfmiddlewaretoken": "{{ csrf_token }}"
                };
                $.post("{% url 'sp_cart:addCart' %}", data, function (data) {
                    if (data.code == 6) {
                        current_num += 1;
                        if (current_num > 0) {
                            self.siblings(".decrease").fadeIn();
                            self.siblings(".text_box").fadeIn();
                        }
                        self.siblings('input').val(current_num);
                        // 修改购物车总数量
                        $("#total_count").text(data.total)
                    } else if (data.code == 1) {
                        {#var rs = confirm(data.msg);#}
                        {#console.debug(rs)#}
                        if (confirm(data.errmsg)) {
                            // js 实现跳转的方法
                            location.href = "{% url 'sp_user:login' %}?next={% url 'sp_goods:商城' cate_id order %}"
                        }
                    } else {
                        alert(data.errmsg);
                    }
                });
            });
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());

                // 通过ajax请求后台, 添加数据库成功
                var sku_id = self.siblings('input').attr('sku_id');
                var data = {
                    "sku_id": sku_id,
                    "count": -1,
                    "csrfmiddlewaretoken": "{{ csrf_token }}"
                };
                $.post("{% url 'sp_cart:addCart' %}", data, function (data) {
                    if (data.code == 6) {
                        current_num -= 1;
                        if (current_num > 0) {
                            self.siblings(".decrease").fadeIn();
                            self.siblings(".text_box").fadeIn();
                        }
                        self.siblings('input').val(current_num);

                        // 修改购物车总数量
                        $("#cart_count").text(data.cart_count)
                    } else if (data.code == 1) {
                        if (confirm(data.errmsg)) {
                            location.href = "{% url 'sp_user:login' %}?next={% url 'sp_goods:商城' cate_id order %}"
                        }
                    }
                });
            });
        });


    </script>
{% endblock %}

SpMarket/templates/sp_goods/detail.html
{% extends 'public/base.html' %}
{% load static %}

{% block head_js %}
		<script>
        	function changeImage(){
              document.getElementById("imgflag").src="images/redherat.png";
           }
        </script>
{% endblock %}

{% block head_css %}
		<style>
			.am-slider-default .am-control-nav{ text-align: center;}
			.am-slider-default .am-control-nav li a.am-active{ background: #cb2527;}
			.am-slider-default .am-control-nav li a{ border: 0; width: 10px; height: 10px;}
		</style>
{% endblock %}

{% block body %}
	<body>
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">商品详情</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <!--图片轮换-->
		<div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
		  <ul class="am-slides">
              {% for f in goodsSku.gallery_set.all %}
              		    <li><img src="{{ MEDIA_URL }}{{ f.img_url }}" /></li>
              {% endfor %}

		  </ul>
		</div>
		<div class="detal-info" style="position: relative; width: 100%;">
			<p>{{ goodsSku.goods_spu.spu_name }}:{{ goodsSku.sku_name }}</p>
			<h2>商城价：<span>￥{{ goodsSku.price }}</span></h2>
			<div class="heart">
				<img src="{% static 'images/herat.png' %}" width="25" id="imgflag" onclick="changeImage()" />
				<p>收藏</p>
			</div>
		</div>
		<div class="d-amount">
        	<h4>数量：</h4>
            <div class="d-stock">
              <a class="decrease">-</a>
                <input id="num" readonly="" sku_id='{{ goodsSku.pk }}' class="text_box" name="" type="text" value="1">
                <a class="increase">+</a>
               <span id="dprice" class="price" style="display:none"> 36</span>
            </div>{{ goodsSku.unit }}
        </div>
        <div style="background: #eee; height: 10px;"></div>
        <div class="am-tabs detail-list" data-am-tabs>
		  <ul class="am-tabs-nav am-nav am-nav-tabs">
		    <li class="am-active"><a href="#tab1">商品详情</a></li>
		    <li><a href="#tab2">商品评论</a></li>
		  </ul>

		  <div class="am-tabs-bd">
		    <div class="am-tab-panel am-fade am-in am-active detail " id="tab1" >
		           {{ goodsSku.goods_spu.content|safe }}
		    </div>
		    <div class="am-tab-panel am-fade detail " id="tab2">
		         <!--<div class="comment">
		         	<span>好评：</span>
		         	<div class="com-good"></div>
		         	<span>100%</span>
		         </div>
		         <div class="comment">
		         	<span>中评：</span>
		         	<div class="com-bad"></div>
		         	<span>0%</span>
		         </div>
		         <div class="comment">
		         	<span>差评：</span>
		         	<div class="com-bad"></div>
		         	<span>0%</span>
		         </div>-->
		         <ul class="comment-list">
		           <li class="current"><a href="">全部</a></li>
		           <li><a href="">好评（20）</a></li>
		           <li><a href="">中评（5）</a></li>
		           <li><a href="">差评（0）</a></li>
		         </ul>
		         <ul class="comment-pic">
		         	<li>
		         		<div class="tit">
		         			<img src="{% static 'images/tx.png' %}" class="tx" />
		         			<span>songke2014</span>
		         			<i> [2016-01-01]</i>
		         		</div>
		         		<div class="comment-con">
		         			买了些给家人，都说不错！
		         		</div>
		         	</li>
		         	<li>
		         		<div class="tit">
		         			<img src="{% static 'images/tx.png' %}" class="tx" />
		         			<span>songke2014</span>
		         			<i> [2016-01-01]</i>
		         		</div>
		         		<div class="comment-con">
		         			买了些给家人，都说不错！
		         		</div>
		         	</li>
		         </ul>
		    </div>
		  </div>
		</div>


		<!--底部-->
 <div style=" height: 55px;"></div>
 <ul class="fix-shopping">
 	<li><a href="{% url 'sp_cart:CartShow' %}" class="join">加入购物车</a></li>
 	<li><a href="{% url 'sp_cart:CartShow' %}" class="imm-buy">立即购买</a></li>
 </ul>
{% endblock %}

 {% block footer_js %}
 <script>
	//购物数量加减
	$(function(){
	    //添加
		$('.increase').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			current_num += 1;
			self.siblings('input').val(current_num);
		})
        //减少
		$('.decrease').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			if(current_num > 1){
				current_num -= 1;
				self.siblings('input').val(current_num);
			}
		})
        $('.join').on('click',function () {
            {#console.debug(111)#}
            var num_input = $('#num');
            var sku_id = num_input.attr('sku_id');
            var count = num_input.val();
            console.debug(sku_id,count)
            $.ajax({
                type:'POST',
                url:'{% url "sp_cart:addCart" %}',
                data:{'sku_id':sku_id,'count':count,'csrfmiddlewaretoken':'{{ csrf_token }}'},
                dataType:'json',
                success:function (data) {
                    if(data.code == 6){
                        alert('添加购物车成功')
                    }else if(data.code == 1){
                        var f = confirm('没有登录,是否进入登录界面?')
                        if(f){
                            location.href = '{% url "sp_user:login" %}?next={% url "sp_goods:详情" goodsSku.pk %}'
                        }
                    }
                }
            })


        })
	})
</script>
 {% endblock %}

SpMarket/templates/sp_goods/index.html
{% extends 'public/base.html' %}
{% load static %}

{% block body %}
		<header data-am-widget="header" class="am-header am-header-default sq-head1">
			<div class="am-header-left am-header-nav">
		        <a href="" class="" style="color: #fff;">
			        <img src="{% static 'images/city.png' %}" />
			        <p style="font-size: 12px; margin-top: -35px;">四川</p>
			    </a>
		   </div>
			<h1 class="am-header-title1">
		        <div class="search-box">
		           <a href="" class="index-search">南昌大学前湖校区∨</a>
		         <!--  <input type="submit" value="" class="search-icon" /> -->
		        </div>
		    </h1>
			<div class="am-header-right am-header-nav">
			    <a href="" class="">
		         <div class="messgae"><span>10</span></div>
		        </a>
			</div>
        </header>
<div style="height: 49px;"></div>
<!--图片轮换-->
<div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
  <ul class="am-slides">
      {% for b in banners %}
          <li><a href="{% url 'sp_goods:详情' b.goods_sku.pk %}" ><img src="{{ MEDIA_URL }}{{ b.img_url }}" /></a></li>
      {% endfor %}
  </ul>
</div>
<!--导航-->
 <ul class="sq-nav">
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/icon.png' %}" />
              <p>充值</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="javascript:;" class="index-qd">
              <img src="{% static 'images/icon1.png' %}" />
              <p>签到</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/icon2.png' %}" />
              <p>红包</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/icon3.png' %}" />
              <p>即将上线</p>
            </a>
        </div>
      </li>
  </ul>
  <ul class="sq-nav1">
  	<li>
        <div class="am-gallery-item">
            <a href="speed.html" class="">
              <img src="{% static 'images/icon4.png' %}" />
              <p>零食飞速</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="{% url 'sp_goods:商城' 0 0 %}" class="">
              <img src="{% static 'images/icon5.png' %}" />
              <p>超市</p>
            </a>
        </div>
      </li>

  </ul>
  <div class="h-line"></div>
  <!--不规则展示-->
  <div class="index-product">
  	<div class="index-pro-lf"><a href="{{ activetys.0.url_site }}"><img src="{{ MEDIA_URL }}{{ activetys.0.img_url }}"/></a></div>
  	<div class="index-pro-lr"><a href=""><img src="{% static 'images/s2.png' %}"  height="130.91"/></a></div>
  </div>
  <div class="product-bot">
  	<div class="product-bot-lf"><a href=""><img src="{% static 'images/s3.png' %}"/></a></div>
  	<div class="product-bot-lr">
  		<div class="top"><a href=""><img src="{% static 'images/s4.png' %}"/></a></div>
  		<div class="bot">
  			<div class="bot-lf"><a href=""><img src="{% static 'images/s5.png' %}"/></a></div>
  			<div class="bot-lr"><a href=""><img src="{% static 'images/s6.png' %}"/></a></div>
  		</div>
  	</div>
  </div>
  <!--不规则展示-->
  <div class="h-line"></div>
  <!-- 特色专区-->
    {% for az in activetys_zone %}
      <div class="sq-title">
 	<img src="{% static 'images/ts.png' %}" width="26"/>
        {{ az.title }}
      </div>

          <ul data-am-widget="gallery" class="am-gallery pro-list am-avg-sm-2 am-avg-md-2 am-avg-lg-4 am-gallery-default"  >
          {% for azg in az.activityzonegoods_set.all %}
           <li>
        <div class="am-gallery-item">
            <a href="{% url 'sp_goods:详情' azg.goods_sku.pk %}" class="">
              <img src=" {{ MEDIA_URL }}{{ azg.goods_sku.logo }}" />
                <h3 class="am-gallery-title">{{ azg.goods_sku.goods_spu.spu_name }}</h3>
                <div class="am-gallery-desc">￥{{ azg.goods_sku.price }}</div>
            </a>
        </div>
      </li>
          {% endfor %}


          </ul>
    {% endfor %}


<!--签到-->
<div class="qd-box">
	<div class="popup-title">
			<span>签到成功</span>
			<div class="popup-close"><i class="iconfont">&#xe602</i></div>
	</div>
	<div class="dq-text">
		<img src="{% static 'images/qiandao.png' %}" width="40" />&nbsp; 您已连续签到3天
	</div>
</div>
<!--签到-->

 <!--底部-->
 <div style="height: 55px;"></div>
 <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
      <ul class="am-navbar-nav am-cf am-avg-sm-5">
          <li>
            <a href="{% url 'sp_goods:首页' %}" class="curr">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
          </li>
          <li>
            <a href="" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
          </li>
          <li>
            <a href="{% url 'sp_cart:CartShow' %}" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
          </li>
          <li>
            <a href="" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
          </li>

          <li>
            <a href="{% url 'sp_user:member' %}" class="">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
          </li>
      </ul>
</div>
{% endblock %}

{% block footer_js %}
 <script type='text/javascript'>
	(function(){
		 new PopUp_api({el:'.index-qd',html:'.qd-box'});
	})()
</script>
{% endblock %}
 
 
 