SpMarket/SpMarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('sp_user.urls',namespace='sp_user')),#用户主页
    url(r'^goods/', include('sp_goods.urls',namespace='sp_goods')),#用户主页
    url(r'^cart/', include('sp_cart.urls',namespace='sp_cart')),#用户主页
    url(r'^order/', include('sp_order.urls',namespace='sp_order')),#用户主页
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),#在主路由中配置 ckeditor 上传文件使用到的url地址
#全文搜索框架
    url(r'^search/', include('haystack.urls')),
]

SpMarket/apps/sp_cart/urls.py
from django.conf.urls import url

from sp_cart.views import AddCartView, CartShowView

urlpatterns = [
    url(r'^addCart/$', AddCartView.as_view(), name="addCart"),
    url(r'^$', CartShowView.as_view(), name="CartShow"),
]

SpMarket/apps/sp_goods/urls.py
from django.conf.urls import url

from sp_goods.views import index , category , detail

urlpatterns = [
    url(r'^$', index, name="首页"),
    url(r'^category/(?P<cate_id>\d+)/(?P<order>\d)$', category, name="商城"),
    url(r'^(?P<id>\d+)$', detail, name="详情"),
]

SpMarket/apps/sp_user/urls.py
from django.conf.urls import url
from sp_user.views import *

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),  # 登录
    url(r'^register/$', RegisterView.as_view(), name='register'),  # 注册
    url(r'^member/$', MemberView.as_view(), name='member'),  # 主页
    url(r'^forget/$', ForgetPassView.as_view(), name='forget'),  # 忘记密码
    url(r'^info/$', InfomationView.as_view(), name='info'),  # 个人资料
    url(r'^sendMsg/$', send_msg_phone, name="sendMsg"),  # 短信地址

]

SpMarket/apps/sp_cart/models.py
from django.db import models

# Create your models here.

SpMarket/apps/sp_cart/views.py
from django.shortcuts import render
# Create your views here.
from django.views import View
from django.http import JsonResponse
from django_redis import get_redis_connection

from db.base_view import BaseVerifyView
from sp_goods.models import GoodsSKU


# 增加
class AddCartView(View):
    def post(self, request):
        user_id = request.session.get('ID')  # 获取登录的ID
        if user_id is None:
            return JsonResponse({'code': 1, 'errmsg': '您还没有登录,请登录'})  # 未登录时的错误提示

        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')  # 接受参数:购物车加入的当前商品ID以及数量

        try:
            sku_id = int(sku_id)
            count = int(count)  # 将接受到的字符串转换为整数
        except:
            return JsonResponse({'code': 2, 'errmsg': '参数错误'})

        try:
            gsku = GoodsSKU.objects.get(pk=sku_id)
        except:
            return JsonResponse({'code': 3, 'errmsg': '商品不存在'})  # 判断商品是否存在

        # if count <= 0:
        #     return JsonResponse({'code': 4, 'errmsg': '请输入正确的商品数量'})  # 判断商品数量

        if gsku.stock < count:
            return JsonResponse({'code': 5, 'errmsg': '该商品库存不足,请重写填写购买数量'})  # 判断库存是否足够

        # 使用redis数据库来添加商品到购物车
        r = get_redis_connection('default')

        ckey = 'cart_key_%s' % user_id

        r.hincrby(ckey, sku_id, count)  # 存储到redis中

        # 计算现在购物车中的商品的数量
        # cart_total = 0
        # vars = r.hvals(ckey)
        # if len(vars) > 0:
        #     for v in vars:
        #         cart_total += int(v)

        return JsonResponse({
            'code': 6,
            # 'cart_total': cart_total
        })

    def get(self, request):
        pass


# 显示购物车
class CartShowView(BaseVerifyView):
    def post(self, request):
        pass

    def get(self, request):
        r = get_redis_connection('default')
        cart_key = 'cart_key_{}'.format(request.session.get('ID'))
        cart_data = r.hgetall(cart_key)
        # 遍历所有购物车信息
        gskus = []
        for sku_id, count in cart_data.items():
            sku_id = int(sku_id)
            count = int(count)

            # 查询购物车商品的完整信息
            gsku = GoodsSKU.objects.get(pk=sku_id)

            # 自定义一个属性保存count
            gsku.count = count

            # 保存
            gskus.append(gsku)
        context = {
            'goodssku': gskus,
        }

        return render(request, "sp_cart/shopcart.html", context)

SpMarket/templates/sp_cart/shopcart.html
{% extends 'public/base.html' %}
{% load static %}
{% block body %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">购物车</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
    <!--购物车空的状态-->
    <div class="login-logo" style="display: {% if goodssku %}
        none
    {% else %}
        block
    {% endif %}">
        <img src="{% static 'images/care.png' %}">
        <p>亲、您的购物车还是空空的哦，快去装满它!</p>
        <a href="index.html" class="goshopping">前去逛逛</a>
    </div>
    <ul class="shopcart-list">
        {% for goods in goodssku %}
            <li>
                <label class="am-checkbox am-warning">
                    <input type="checkbox" checked="checked" value="" data-am-ucheck checked>
                </label>
                <a href="{% url 'sp_goods:详情' goods.pk %}"><img src="{{ MEDIA_URL }}{{ goods.logo }}" class="shop-pic"/></a>
                <div class="shop-list-mid">
                    <div class="tit"><a href="{% url 'sp_goods:详情' goods.pk %}">
                        {{ goods.goods_spu.spu_name }}&emsp;{{ goods.sku_name }} 包邮</a></div>
                    <b class="shop-list-price">￥<span class="price">{{ goods.price }}</span> </b>
                </div>
                <div class="list-cart1">
                    <div class="d-stock">
                        <a class="decrease">-</a>
                        <input readonly=""  sku_id = "{{ goods.pk }}" class="text_box num" name="" type="text" value="{{ goods.count }}">
                        <a class="increase">+</a>
                    </div>
                </div>

            </li>
        {% endfor %}


        <div style="height: 10px; background: #eee;"></div>
    </ul>

    <div class="shop-fix">

        <label class="am-checkbox am-warning">
            <input type="checkbox" checked="checked" value="" data-am-ucheck checked>
        </label>
        <a class="del">全选</a>
        <a href="tureorder.html" class="js-btn">去结算</a>
        <div class="js-text">
            <P>合计：￥<b id="sum">00.00</b></P>
            <p class="js-car">免费配送</p>
        </div>
    </div>

    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="{% url 'sp_goods:首页' %}" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="shopcart.html" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="allorder.html" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="{% url 'sp_user:member' %}" class="curr">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}

{% block footer_js %}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;
                self.siblings('input').val(current_num);
                var sku_id = self.siblings('input').attr('sku_id');
                $.ajax({
                    type: 'post',
                    url: '{% url "sp_cart:addCart" %}',
                    data: {
                        "count": 1,
                        "sku_id": sku_id,
                        "csrfmiddlewaretoken": "{{ csrf_token }}",
                    },
                    dataType: "json",
                    success: function (data) {
                        if (data.code == 6) {
                            current_num += 1;
                            self.siblings('input').val(current_num);

                            //重新计算价格
                            Sum();
                        }
                    }
                });
            })
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 1) {
                    current_num -= 1;
                    self.siblings('input').val(current_num);
                }
                var sku_id = self.siblings('input').attr('sku_id');
                $.ajax({
                    type: 'post',
                    url: '{% url "sp_cart:addCart" %}',
                    data: {
                        "count": -1,
                        "sku_id": sku_id,
                        "csrfmiddlewaretoken": "{{ csrf_token }}",
                    },
                    dataType: "json",
                    success: function (data) {
                        if (data.code == 6) {
                            if (current_num > 1) {
                                current_num -= 1;
                                self.siblings('input').val(current_num);
                            } else if (current_num == 1) {
                                //当前li被删除
                                self.parents('li').remove();
                                //如果所有的li都被删除了, 购物车就要显示出来
                                if ($(".shopcart-list").find('li').length == 0) {
                                    //购物车显示出来
                                    $(".cart_logo").show();
                                }
                            }

                            //重新计算价格
                            Sum();
                        }
                    }
                });
            })

            function Sum() {
                var checkeds = $(".shopcart-list").find(":checked")
                var total_price = 0;
                var total_count = 0;
                var sum = 0;
                $.each(checkeds, function (i, e) {
                    {#console.debug(i,e)#}
                    var li = $(e).parents("li");
                    {#console.debug(li);#}
                    total_price = li.find(".price").text();
                    total_count = li.find('.num').val();
                    {#console.debug((total_price,total_count))#}
                    sum += total_count * total_price
                });
                $('#sum').text(sum.toFixed(2));

            }

            Sum()
        })
    </script>
{% endblock %}