SpMarket/SpMarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('sp_user.urls',namespace='sp_user')),#用户主页
    url(r'^goods/', include('sp_goods.urls',namespace='sp_goods')),#用户主页
    url(r'^cart/', include('sp_cart.urls',namespace='sp_cart')),#用户主页
    url(r'^order/', include('sp_order.urls',namespace='sp_order')),#用户主页
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),#在主路由中配置 ckeditor 上传文件使用到的url地址
#全文搜索框架
    url(r'^search/', include('haystack.urls')),
]

SpMarket/apps/sp_order/urls.py
from django.conf.urls import url

from sp_order.views import GlAddressView, AddressView

urlpatterns = [
    url('^gladd$',GlAddressView.as_view(),name='选择收货地址'),
    url('^add$',AddressView.as_view(),name='添加收货地址'),
]

SpMarket/apps/sp_order/models.py
from django.db import models
from db.base_model import BaseModel
from sp_user.models import Users

# Create your models here.
class UserAddress(BaseModel):
    """用户收货地址管理"""
    user = models.ForeignKey(to="sp_user.Users", verbose_name="创建人")
    username = models.CharField(verbose_name="收货人", max_length=100)
    phone = models.CharField(verbose_name="收货人电话", max_length=11)
    hcity = models.CharField(verbose_name="省", max_length=100)
    hproper = models.CharField(verbose_name="市", max_length=100, blank=True, default='')
    harea = models.CharField(verbose_name="区", max_length=100, blank=True, default='')
    brief = models.CharField(verbose_name="详细地址", max_length=255)
    isDefault = models.BooleanField(verbose_name="是否设置为默认", default=False, blank=True)

    class Meta:
        verbose_name = "收货地址管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username

SpMarket/apps/sp_order/forms.py
from django import forms
from django.core import validators

from sp_order.models import UserAddress


class AddressAddForm(forms.ModelForm):
    """用户添加收货地址的表单"""

    class Meta:
        model = UserAddress
        exclude = ['create_time', 'update_time', 'is_delete', 'user']
        error_messages = {
            'username': {
                'required': "请填写用户名！",
            },
            'phone': {
                'required': "请填写手机号码！",
            },
            'brief': {
                'required': "请填写详细地址！",
            },
            'hcity': {
                'required': "请填写完整地址！",
            },
            'hproper': {
                'required': "请填写完整地址！",
            },
            'harea': {
                'required': "请填写完整地址！",
            },
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 验证手机号码格式错误
        self.fields['phone'].validators.append(validators.RegexValidator(r'^1[3-9]\d{9}$', '手机号码格式错误'))

    def clean(self):
        # 验证如果数据库里地址已经超过6六表报错
        cleaned_data = super().clean()
        count = UserAddress.objects.filter(user_id=self.data.get("user_id")).count()
        if count >= 6:
            raise forms.ValidationError({"hcity": "收货地址最多只能保存6条"})
        return cleaned_data

SpMarket/apps/sp_order/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View


class GlAddressView(View):
    def post(self, request):
        pass

    def get(self, request):
        return render(request, 'sp_order/gladdress.html')

class AddressView(View):
    def post(self,request):
        return render(request,'sp_order/address.html')
    def get(self,request):
        return render(request,'sp_order/address.html')

SpMarket/templates/sp_order/address.html
{% extends 'public/base.html' %}
{% load static %}
{% block head_js %}
    <script src="{% static 'js/area.js' %}"></script>
    <link href="http://static.h-ui.net/h-ui/css/H-ui.min.css" rel="stylesheet" type="text/css" />

    <style type="text/css">
html,body{height:auto;}
#province select{margin-left:10px; width:100px}
</style>
{% endblock %}

{% block body %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">新增收货地址</a>
            </h1>
	    </header>
	    <div style="height: 60px;"></div>
	    <ul class="address">
                        <div id="province"></div>
	    	<li><input type="text" class="add-input" placeholder="你在哪"  /></li>
	    	<li><input type="text" class="add-input" placeholder="收货人" /></li>
	    	<li><input type="text" class="add-input" placeholder="请输入手机号码" /></li>
	    </ul>
	    <div class="moren">
	    	<label class="am-checkbox am-warning">
                 <input type="checkbox" checked="checked" value="" data-am-ucheck checked>设为默认
            </label>

	    </div>
	    <input type="button" class="login-btn" value="确认提交">
{% endblock %}

{% block footer_js %}
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'jquery.provincesCity.js' %}"></script>
<script type="text/javascript" src="{% static 'provincesData.js' %}"></script>
<script type="text/javascript">
/*调用插件*/
$(function(){
	$("#province").ProvinceCity();
});
</script>
{% endblock %}

SpMarket/templates/sp_order/gladdress.html
{% extends 'public/base.html' %}
{% load static %}

{% block body %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">管理收货地址</a>
            </h1>
            <div class="am-header-right am-header-nav">
				<a href="{% url 'sp_order:添加收货地址' %}" class="">
					<i class="am-icon-plus"></i>
				</a>
			</div>
	    </header>
	    <div style="height: 49px;"></div>
	    <ul class="address-list">
	    	<li class="curr">
	    		<p>收货人：徐女士&nbsp;&nbsp;182********</p>
	    		<p class="order-add1">收货地址：江西省南昌市 青云谱区解放西路258号江西省南昌市 青云谱区解放西路258号</p>
	    	    <hr />
	    	    <div class="address-cz">
	    	    	<label class="am-radio am-warning">
                       <input type="radio" name="radio3" value="" data-am-ucheck checked> 设为默认
                    </label>
                    <a href=""><img src="{% static 'images/bj.png' %}" width="18" />&nbsp;编辑</a>
                    <a href="">删除</a>
	    	    </div>
	    	</li>
	    </ul>
{% endblock %}